### PR TITLE
Add pyproject.toml

### PR DESCRIPTION
**Pull request by FlorisHoogenboom**
In the past there have been some issues raised on not being able to easilly install `tslearn` via `pip` (see e.g. #84 and #132). Even though these issues are closed there is an easy fix for this given by [PEP-518](https://www.python.org/dev/peps/pep-0518/). This PR adds a `pyproject.toml` file which makes it possible to install `tslearn` from source by simply using `pip`.

I'm curious to hear any feedback on the idea of including this.

### CODE REVIEW

**Comment by rth** [comment]
+1 to use `pyproject.toml` to imporve installation experience.

**Comment by rth** [comment]
Generally LGTM, but let's fix CI first in https://github.com/rtavenar/tslearn/pull/190 then merge master into this PR to check that all tests work as expected.

**Comment by rtavenar** [comment]
> Generally LGTM, but let's fix CI first in #190 then merge master into this PR to check that all tests work as expected.

OK, thanks for your feedback on this point, and I agree that merging #190 is the first thing to do: will do asa Travis passes for Python3*

**Comment by rtavenar** [comment]
Is there something to be added to the docs so that this `pyproject.toml` is taken into account at build time?

**Comment by rth** [comment]
> Is there something to be added to the docs so that this pyproject.toml is taken into account at build time?

No it should be automatic with recent pip versions.

**Pull request merged**
