### PR TITLE
Add utilities to cast from/to other python time series packages

### PR DESCRIPTION
**Pull request by rtavenar**
The idea is to have a way to easily cast time series datasets from/to tslearn format to/from formats used by other python time series libraries.

I started with `pyts`. @johannfaouzi could you tell if what I assume to be the type of `pyts` datasets is OK or not?

The full list I would like to have would be:
* [x] pyts
* [x] sktime
* [x] cesium-ml
* [x] seglearn
* [x] tsfresh
* [x] stumpy
* [x] pyflux

### CODE REVIEW

**Comment by johannfaouzi** [comment]
pyts can deal with multivariate time series, although most of the provided features are for univariate time series for the moment.

pyts convention:
* univariate: (n_ts, sz)
* multivariate: (n_ts, d, sz)

The first axis is always the sample axis and the last axis is always the time axis.

**Comment by rtavenar** [comment]
OK, thanks, I will change that.
Romain Tavenard
Maître de conférences / Assistant professor
Univ. Rennes - LETG
Tél. / Phone : +33 2 99 14 18 04
http://rtavenar.github.io/research/ <http://rtavenar.github.io/research/>

**Comment by johannfaouzi** [comment]
A PR from Hicham Janati was merged into master last week that extends the use of DTW and DTW-related stuff (constraint regions, DTW variants) to variable length time series. So most of the pyts.metrics module can deal with variable length time series, but not the other modules.

I will try to check it out tomorrow or the day after!

**Comment by rtavenar** [comment]
OK, I do not really need to know which algos support them. But are they supposed to be encoded just as in tslearn (NaN padded at the end of shorter time series, or is it done another way?

In other words, if I have a dataset that would contain 2 time series: `[1, 2, 3]` and `[1, 2]`: would it be formatted like:
```
[[1, 2, 3    ],
 [1, 2, nan]]
```

or another way (list of arrays, etc)?

**Comment by rtavenar** [comment]
For `sktime`, info is available there: https://alan-turing-institute.github.io/sktime/examples/loading_data.html

**Comment by rtavenar** [comment]
Seems that for `sktime` and `tsfresh`, `pandas` dataframes are used. At the moment, pandas is not a dependency for `tslearn`, and I would prefer not to add hard dependencies if possible, but having a soft-dependency that is required only if casting to those formats would probably make sense.

**Comment by johannfaouzi** [comment]
> OK, I do not really need to know which algos support them. But are they supposed to be encoded just as in tslearn (NaN padded at the end of shorter time series, or is it done another way?
> 
> In other words, if I have a dataset that would contain 2 time series: `[1, 2, 3]` and `[1, 2]`: would it be formatted like:
> 
> ```
> [[1, 2, 3  ],
>  [1, 2, nan]]
> ```
> 
> or another way (list of arrays, etc)?

For the moment it is not supported at all. I would like to have two different values for missing and padding values (probably `np.nan ` for missing values and maybe `np.inf` for padding values). Except for DTW-related stuff, nothing in `pyts` can currently deal with variable length time series (and for practical reasons I think that it will stay like this for most algorithms that are not related to DTW).

Conclusion: not yet supported, should be supported soon for KNN with DTW, will keep you updated

**Comment by rtavenar** [comment]
@johannfaouzi : thanks for the detailed answer. 

So, is that OK for you if, for the moment, we have a check in `tslearn` that the dataset is made of equal-length time series and later (when it is supported in `pyts`), we change the conversion functions to mirror the change?

**Pull request merged**
