### PR TITLE
[MRG] DOC: Add contributing guide

### PR DESCRIPTION
**Pull request by johannfaouzi**
This PR is identical to #197 expect that the target branch is `master` instead of `dev`.

By the way did you have news from RTD? It does not seem to build the documentation for PR. If they have activated the feature for this project, you have to configure the webhook (see [at the bottom of this page](https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html)).

### CODE REVIEW

**Comment by rtavenar** [comment]
The webhook seems to be configured properly, but it doesn't work, I'll check later.

**Comment by rtavenar** [comment]
@johannfaouzi do you know where to find rtd oauth app ?

According to this page:https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html
it seems to be required for things to work properly... I have gone through all the other steps.

**Comment by johannfaouzi** [comment]
In the settings, in the webhooks section:

Capture d’écran 2020-04-04 à 17 04 06

Capture d’écran 2020-04-04 à 17 04 32

Did you get the confirmation email from the support of RTD? If they didn't reply to your email, they probably didn't enable the feature yet.

**Comment by rtavenar** [comment]
This is set up, and I received the answer by email yeh, so maybe i should wait for the next pr




Sent from a mobile device. Please excuse my brevity. 







On Sat, Apr 4, 2020 at 5:06 PM +0200, "Johann Faouzi" <notifications@github.com> wrote:
















In the settings, in the webhooks section:











Did you get the confirmation email from the support of RTD? If they didn't reply to your email, they probably didn't enable the feature yet.

**Pull request merged**
